services:
  - type: web
    name: grindtheclip
    env: python
    region: frankfurt
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    healthCheckPath: /health
    envVars:
      - key: SECRET_KEY
        generateValue: true
